export const CARGAR_USUARIO = 'CARGAR_USUARIO'
export const LOGOUT = 'LOGOUT'
export const MOSTRAR_NOTIFICACION = 'MOSTRAR_NOTIFICACION'
export const MOSTRAR_LOADER = 'MOSTRAR_LOADER'
export const PLAY_SOUND = "PLAY_SOUND"
